Minify json
ttu/json-flatfile-datastore pull request #73
Opened 2022-10-19 15:11 UTC by BlackBooth

As suggested in issue #71, added the possibility to minify the json output.

2022-10-21 05:24 UTC, ttu requested changes
Thanks! Can you add a test for this. I added a test for non minified version
https://github.com/ttu/json-flatfile-datastore/blob/37a2c0a795257b0600ee8d0362cb0d4e264e1a27/JsonFlatFileDataStore.Test/DataStoreTests.cs#L478

This way we can validate that this also works when we have `useLowerCamelCase` as false.

2022-10-21 05:24 UTC, ttu commented on JsonFlatFileDataStore/DataStore.cs
> -                    break;
This is now  part of another PR and can be removed from this PR

2022-10-21 11:39 UTC, BlackBooth commented
Merged from master, added test and fixed a bug.

2022-10-23 05:54 UTC, ttu requested changes
Looks good! Few minor improvements we could make.

Besides those we should also update the documentation. You can make the changes in this PR or I can make updates those later.
* Add this change to CHANGELOD: https://github.com/ttu/json-flatfile-datastore/blob/master/CHANGELOG.md
* Update README: https://github.com/ttu/json-flatfile-datastore#writing-to-file

2022-10-23 05:54 UTC, ttu commented on JsonFlatFileDataStore.Test/DataStoreTests.cs
> +        [InlineData(true, true)]
We can add allowedLengths as a parameter, then no need to separate logic in the test

```cs
[InlineData(true, true, new [] { 40 } )]
```

2022-10-23 05:54 UTC, ttu commented on JsonFlatFileDataStore.Test/DataStoreTests.cs
> +            // Length on Windows is 81 and on Linux 74
You can add to comments a minified example

2022-10-23 05:54 UTC, ttu commented on JsonFlatFileDataStore/DataStore.cs
> +                            return JsonConvert.SerializeObject(jObject, minifyJson ? Formatting.None: Formatting.Indented, _serializerSettings);
Selected formatting could be done before setting `_toJsonFunc`.

```
var usedFormatting = minifyJson ? Formatting.None: Formatting.Indented;
```

Then there is no need to have conditional check every time function is executed.

2022-10-26 13:55 UTC, BlackBooth commented
I've added the suggested changes.

One question came to my mind: Should encrypted output always be minified, since nobody can read the output anyways?

2022-10-29 03:47 UTC, merged

2022-10-29 03:47 UTC, ttu commented
>  Should encrypted output always be minified, since nobody can read the output anyways?