Always minify when encryption is used
ttu/json-flatfile-datastore pull request #76
Opened 2022-11-02 15:16 UTC by BlackBooth

As suggested, the output ist minified when encryption is used, since nobody can read the output anyways. Test is included

2022-11-04 20:01 UTC, ttu requested changes
Thanks for the PR. Just one minor change request.

2022-11-05 12:50 UTC, BlackBooth commented on JsonFlatFileDataStore/DataStore.cs
> +                usedFormatting = Formatting.None;
Good idea, but then I also swapped the logic for the `if (!useEncryption)` to `if (useEncryption)` for better readability (no need to invert the if-clause)

2022-11-06 14:52 UTC, ttu commented on JsonFlatFileDataStore/DataStore.cs
> +                usedFormatting = Formatting.None;
Thanks! Yes, it is always to good use positive logic in condition checks 👍

2022-11-06 14:53 UTC, ttu approved these changes

2022-11-09 06:28 UTC, BlackBooth commented
Will you merge it?

2022-11-13 06:19 UTC, merged

2022-11-13 06:22 UTC, ttu commented
Thanks! Added an update to changelog and merged 👍